name: codegen
description: A Helm charts for Kubernetes application
version: 0.0.0
home: https://k8s.community/
sources:
  - https://github.com/k8s-community/codegen
maintainers:
  - name: Kubernetes Community Authors
    email: k8s.community@gmail.com
engine: gotpl
